// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgSendSendDrug } from "./types/traceability/traceability/tx";
import { MsgSendRequestShip } from "./types/traceability/traceability/tx";
import { MsgSendForbidShip } from "./types/traceability/traceability/tx";
import { MsgSendDestroyDrug } from "./types/traceability/traceability/tx";
import { MsgSendAllowShip } from "./types/traceability/traceability/tx";


export { MsgSendSendDrug, MsgSendRequestShip, MsgSendForbidShip, MsgSendDestroyDrug, MsgSendAllowShip };

type sendMsgSendSendDrugParams = {
  value: MsgSendSendDrug,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendRequestShipParams = {
  value: MsgSendRequestShip,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendForbidShipParams = {
  value: MsgSendForbidShip,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendDestroyDrugParams = {
  value: MsgSendDestroyDrug,
  fee?: StdFee,
  memo?: string
};

type sendMsgSendAllowShipParams = {
  value: MsgSendAllowShip,
  fee?: StdFee,
  memo?: string
};


type msgSendSendDrugParams = {
  value: MsgSendSendDrug,
};

type msgSendRequestShipParams = {
  value: MsgSendRequestShip,
};

type msgSendForbidShipParams = {
  value: MsgSendForbidShip,
};

type msgSendDestroyDrugParams = {
  value: MsgSendDestroyDrug,
};

type msgSendAllowShipParams = {
  value: MsgSendAllowShip,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgSendSendDrug({ value, fee, memo }: sendMsgSendSendDrugParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendSendDrug: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendSendDrug({ value: MsgSendSendDrug.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendSendDrug: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendRequestShip({ value, fee, memo }: sendMsgSendRequestShipParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendRequestShip: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendRequestShip({ value: MsgSendRequestShip.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendRequestShip: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendForbidShip({ value, fee, memo }: sendMsgSendForbidShipParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendForbidShip: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendForbidShip({ value: MsgSendForbidShip.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendForbidShip: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendDestroyDrug({ value, fee, memo }: sendMsgSendDestroyDrugParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendDestroyDrug: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendDestroyDrug({ value: MsgSendDestroyDrug.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendDestroyDrug: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgSendAllowShip({ value, fee, memo }: sendMsgSendAllowShipParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgSendAllowShip: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgSendAllowShip({ value: MsgSendAllowShip.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgSendAllowShip: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgSendSendDrug({ value }: msgSendSendDrugParams): EncodeObject {
			try {
				return { typeUrl: "/traceability.traceability.MsgSendSendDrug", value: MsgSendSendDrug.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendSendDrug: Could not create message: ' + e.message)
			}
		},
		
		msgSendRequestShip({ value }: msgSendRequestShipParams): EncodeObject {
			try {
				return { typeUrl: "/traceability.traceability.MsgSendRequestShip", value: MsgSendRequestShip.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendRequestShip: Could not create message: ' + e.message)
			}
		},
		
		msgSendForbidShip({ value }: msgSendForbidShipParams): EncodeObject {
			try {
				return { typeUrl: "/traceability.traceability.MsgSendForbidShip", value: MsgSendForbidShip.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendForbidShip: Could not create message: ' + e.message)
			}
		},
		
		msgSendDestroyDrug({ value }: msgSendDestroyDrugParams): EncodeObject {
			try {
				return { typeUrl: "/traceability.traceability.MsgSendDestroyDrug", value: MsgSendDestroyDrug.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendDestroyDrug: Could not create message: ' + e.message)
			}
		},
		
		msgSendAllowShip({ value }: msgSendAllowShipParams): EncodeObject {
			try {
				return { typeUrl: "/traceability.traceability.MsgSendAllowShip", value: MsgSendAllowShip.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgSendAllowShip: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			TraceabilityTraceability: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;