// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: traceability/traceability/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetTraceinfoRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetTraceinfoRequest) Reset()         { *m = QueryGetTraceinfoRequest{} }
func (m *QueryGetTraceinfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetTraceinfoRequest) ProtoMessage()    {}
func (*QueryGetTraceinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{2}
}
func (m *QueryGetTraceinfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTraceinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTraceinfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTraceinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTraceinfoRequest.Merge(m, src)
}
func (m *QueryGetTraceinfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTraceinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTraceinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTraceinfoRequest proto.InternalMessageInfo

func (m *QueryGetTraceinfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetTraceinfoResponse struct {
	Traceinfo Traceinfo `protobuf:"bytes,1,opt,name=Traceinfo,proto3" json:"Traceinfo"`
}

func (m *QueryGetTraceinfoResponse) Reset()         { *m = QueryGetTraceinfoResponse{} }
func (m *QueryGetTraceinfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetTraceinfoResponse) ProtoMessage()    {}
func (*QueryGetTraceinfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{3}
}
func (m *QueryGetTraceinfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetTraceinfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetTraceinfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetTraceinfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetTraceinfoResponse.Merge(m, src)
}
func (m *QueryGetTraceinfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetTraceinfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetTraceinfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetTraceinfoResponse proto.InternalMessageInfo

func (m *QueryGetTraceinfoResponse) GetTraceinfo() Traceinfo {
	if m != nil {
		return m.Traceinfo
	}
	return Traceinfo{}
}

type QueryAllTraceinfoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTraceinfoRequest) Reset()         { *m = QueryAllTraceinfoRequest{} }
func (m *QueryAllTraceinfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllTraceinfoRequest) ProtoMessage()    {}
func (*QueryAllTraceinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{4}
}
func (m *QueryAllTraceinfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTraceinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTraceinfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTraceinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTraceinfoRequest.Merge(m, src)
}
func (m *QueryAllTraceinfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTraceinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTraceinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTraceinfoRequest proto.InternalMessageInfo

func (m *QueryAllTraceinfoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllTraceinfoResponse struct {
	Traceinfo  []Traceinfo         `protobuf:"bytes,1,rep,name=Traceinfo,proto3" json:"Traceinfo"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllTraceinfoResponse) Reset()         { *m = QueryAllTraceinfoResponse{} }
func (m *QueryAllTraceinfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllTraceinfoResponse) ProtoMessage()    {}
func (*QueryAllTraceinfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{5}
}
func (m *QueryAllTraceinfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllTraceinfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllTraceinfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllTraceinfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllTraceinfoResponse.Merge(m, src)
}
func (m *QueryAllTraceinfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllTraceinfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllTraceinfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllTraceinfoResponse proto.InternalMessageInfo

func (m *QueryAllTraceinfoResponse) GetTraceinfo() []Traceinfo {
	if m != nil {
		return m.Traceinfo
	}
	return nil
}

func (m *QueryAllTraceinfoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetPhtraceinfoRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetPhtraceinfoRequest) Reset()         { *m = QueryGetPhtraceinfoRequest{} }
func (m *QueryGetPhtraceinfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetPhtraceinfoRequest) ProtoMessage()    {}
func (*QueryGetPhtraceinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{6}
}
func (m *QueryGetPhtraceinfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPhtraceinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPhtraceinfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPhtraceinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPhtraceinfoRequest.Merge(m, src)
}
func (m *QueryGetPhtraceinfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPhtraceinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPhtraceinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPhtraceinfoRequest proto.InternalMessageInfo

func (m *QueryGetPhtraceinfoRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetPhtraceinfoResponse struct {
	Phtraceinfo Phtraceinfo `protobuf:"bytes,1,opt,name=Phtraceinfo,proto3" json:"Phtraceinfo"`
}

func (m *QueryGetPhtraceinfoResponse) Reset()         { *m = QueryGetPhtraceinfoResponse{} }
func (m *QueryGetPhtraceinfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetPhtraceinfoResponse) ProtoMessage()    {}
func (*QueryGetPhtraceinfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{7}
}
func (m *QueryGetPhtraceinfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetPhtraceinfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetPhtraceinfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetPhtraceinfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetPhtraceinfoResponse.Merge(m, src)
}
func (m *QueryGetPhtraceinfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetPhtraceinfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetPhtraceinfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetPhtraceinfoResponse proto.InternalMessageInfo

func (m *QueryGetPhtraceinfoResponse) GetPhtraceinfo() Phtraceinfo {
	if m != nil {
		return m.Phtraceinfo
	}
	return Phtraceinfo{}
}

type QueryAllPhtraceinfoRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPhtraceinfoRequest) Reset()         { *m = QueryAllPhtraceinfoRequest{} }
func (m *QueryAllPhtraceinfoRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllPhtraceinfoRequest) ProtoMessage()    {}
func (*QueryAllPhtraceinfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{8}
}
func (m *QueryAllPhtraceinfoRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPhtraceinfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPhtraceinfoRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPhtraceinfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPhtraceinfoRequest.Merge(m, src)
}
func (m *QueryAllPhtraceinfoRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPhtraceinfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPhtraceinfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPhtraceinfoRequest proto.InternalMessageInfo

func (m *QueryAllPhtraceinfoRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllPhtraceinfoResponse struct {
	Phtraceinfo []Phtraceinfo       `protobuf:"bytes,1,rep,name=Phtraceinfo,proto3" json:"Phtraceinfo"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllPhtraceinfoResponse) Reset()         { *m = QueryAllPhtraceinfoResponse{} }
func (m *QueryAllPhtraceinfoResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllPhtraceinfoResponse) ProtoMessage()    {}
func (*QueryAllPhtraceinfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_950b90ce1038f089, []int{9}
}
func (m *QueryAllPhtraceinfoResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllPhtraceinfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllPhtraceinfoResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllPhtraceinfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllPhtraceinfoResponse.Merge(m, src)
}
func (m *QueryAllPhtraceinfoResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllPhtraceinfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllPhtraceinfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllPhtraceinfoResponse proto.InternalMessageInfo

func (m *QueryAllPhtraceinfoResponse) GetPhtraceinfo() []Phtraceinfo {
	if m != nil {
		return m.Phtraceinfo
	}
	return nil
}

func (m *QueryAllPhtraceinfoResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "traceability.traceability.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "traceability.traceability.QueryParamsResponse")
	proto.RegisterType((*QueryGetTraceinfoRequest)(nil), "traceability.traceability.QueryGetTraceinfoRequest")
	proto.RegisterType((*QueryGetTraceinfoResponse)(nil), "traceability.traceability.QueryGetTraceinfoResponse")
	proto.RegisterType((*QueryAllTraceinfoRequest)(nil), "traceability.traceability.QueryAllTraceinfoRequest")
	proto.RegisterType((*QueryAllTraceinfoResponse)(nil), "traceability.traceability.QueryAllTraceinfoResponse")
	proto.RegisterType((*QueryGetPhtraceinfoRequest)(nil), "traceability.traceability.QueryGetPhtraceinfoRequest")
	proto.RegisterType((*QueryGetPhtraceinfoResponse)(nil), "traceability.traceability.QueryGetPhtraceinfoResponse")
	proto.RegisterType((*QueryAllPhtraceinfoRequest)(nil), "traceability.traceability.QueryAllPhtraceinfoRequest")
	proto.RegisterType((*QueryAllPhtraceinfoResponse)(nil), "traceability.traceability.QueryAllPhtraceinfoResponse")
}

func init() {
	proto.RegisterFile("traceability/traceability/query.proto", fileDescriptor_950b90ce1038f089)
}

var fileDescriptor_950b90ce1038f089 = []byte{
	// 604 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xc7, 0x73, 0x69, 0x89, 0xc4, 0x15, 0x75, 0x38, 0x3a, 0xb4, 0x06, 0x19, 0x7a, 0x94, 0xd0,
	0x34, 0xed, 0x9d, 0xd2, 0x50, 0x16, 0x06, 0x94, 0x0e, 0x94, 0x09, 0x85, 0x08, 0x31, 0xb0, 0x9d,
	0x9b, 0xc3, 0x58, 0x72, 0x7c, 0x6e, 0xec, 0x22, 0x22, 0xc4, 0xc2, 0x5f, 0x80, 0xe0, 0x8f, 0x40,
	0x2c, 0x20, 0x16, 0xfe, 0x86, 0x8e, 0x95, 0x58, 0x3a, 0x21, 0x94, 0xf0, 0x87, 0xa0, 0xdc, 0x5d,
	0x12, 0x3b, 0xb1, 0x63, 0xb7, 0x74, 0xcb, 0x5d, 0xbe, 0xef, 0xbd, 0xcf, 0xfb, 0x71, 0xcf, 0xf0,
	0x6e, 0xd8, 0x65, 0x87, 0x9c, 0x59, 0x8e, 0xeb, 0x84, 0x3d, 0x1a, 0x3b, 0x1c, 0x1d, 0xf3, 0x6e,
	0x8f, 0xf8, 0x5d, 0x11, 0x0a, 0xb4, 0x16, 0xfd, 0x87, 0x44, 0x0f, 0xc6, 0x8a, 0x2d, 0x6c, 0x21,
	0x55, 0x74, 0xf8, 0x4b, 0x19, 0x18, 0x37, 0x6d, 0x21, 0x6c, 0x97, 0x53, 0xe6, 0x3b, 0x94, 0x79,
	0x9e, 0x08, 0x59, 0xe8, 0x08, 0x2f, 0xd0, 0xff, 0x6e, 0x1d, 0x8a, 0xa0, 0x23, 0x02, 0x6a, 0xb1,
	0x80, 0xab, 0x38, 0xf4, 0x4d, 0xcd, 0xe2, 0x21, 0xab, 0x51, 0x9f, 0xd9, 0x8e, 0x27, 0xc5, 0x5a,
	0x5b, 0x4e, 0x27, 0xf4, 0x59, 0x97, 0x75, 0x46, 0x3e, 0x2b, 0xe9, 0x3a, 0x79, 0x70, 0xbc, 0x57,
	0x23, 0xb8, 0xea, 0x1c, 0x97, 0xaf, 0xa7, 0xc4, 0x78, 0x05, 0xa2, 0x67, 0x43, 0xc2, 0xa6, 0x0c,
	0xd6, 0xe2, 0x47, 0xc7, 0x3c, 0x08, 0xf1, 0x0b, 0x78, 0x3d, 0x76, 0x1b, 0xf8, 0xc2, 0x0b, 0x38,
	0x7a, 0x04, 0x4b, 0x0a, 0x6a, 0x15, 0xdc, 0x06, 0x9b, 0x4b, 0xbb, 0xeb, 0x24, 0xb5, 0x70, 0x44,
	0x99, 0xee, 0x2f, 0x9e, 0xfc, 0xbe, 0x55, 0x68, 0x69, 0x33, 0xbc, 0x05, 0x57, 0xa5, 0xdf, 0x03,
	0x1e, 0x3e, 0x1f, 0x81, 0xe8, 0x98, 0x68, 0x19, 0x16, 0x9d, 0xb6, 0x74, 0xbc, 0xd8, 0x2a, 0x3a,
	0x6d, 0xcc, 0xe1, 0x5a, 0x82, 0x56, 0x93, 0x3c, 0x81, 0x57, 0xc7, 0x97, 0x1a, 0x66, 0x63, 0x0e,
	0xcc, 0x58, 0xab, 0x79, 0x26, 0xc6, 0xd8, 0xd2, 0x48, 0x0d, 0xd7, 0x9d, 0x41, 0x7a, 0x0c, 0xe1,
	0xa4, 0x61, 0x3a, 0x4c, 0x99, 0xa8, 0xee, 0x92, 0x61, 0x77, 0x89, 0x9a, 0x22, 0xdd, 0x5d, 0xd2,
	0x64, 0x36, 0xd7, 0xb6, 0xad, 0x88, 0x25, 0xfe, 0x06, 0x74, 0x2e, 0xf1, 0x20, 0xc9, 0xb9, 0x2c,
	0x5c, 0x38, 0x17, 0x74, 0x10, 0xe3, 0x2d, 0x4a, 0xde, 0x7b, 0x99, 0xbc, 0x0a, 0x23, 0x06, 0xbc,
	0x0d, 0x8d, 0x51, 0xed, 0x9b, 0x93, 0x91, 0x49, 0xeb, 0x54, 0x07, 0xde, 0x48, 0x54, 0xeb, 0xfc,
	0x9e, 0xc2, 0xa5, 0xc8, 0xf5, 0xb8, 0x8c, 0x73, 0x46, 0x67, 0xa2, 0xd6, 0x39, 0x46, 0x1d, 0xe0,
	0xb6, 0x86, 0x6b, 0xb8, 0x6e, 0x02, 0xdc, 0x65, 0xf5, 0xec, 0x27, 0xd0, 0x59, 0x4d, 0x87, 0x49,
	0xcb, 0x6a, 0xe1, 0xbf, 0xb2, 0xba, 0xb4, 0xde, 0xed, 0x9e, 0x95, 0xe0, 0x15, 0x09, 0x8e, 0x3e,
	0x01, 0x58, 0x52, 0xcf, 0x10, 0xed, 0xcc, 0x01, 0x9b, 0x7d, 0xff, 0x06, 0xc9, 0x2b, 0x57, 0xf1,
	0x71, 0xe5, 0xc3, 0xaf, 0xbf, 0x9f, 0x8b, 0x77, 0xd0, 0x3a, 0xcd, 0x5a, 0x67, 0xe8, 0x2b, 0x88,
	0x8c, 0x3b, 0xaa, 0x67, 0x05, 0x4a, 0xd8, 0x14, 0xc6, 0xfd, 0xf3, 0x19, 0x69, 0xc6, 0x9a, 0x64,
	0xac, 0xa2, 0x0a, 0xcd, 0xb1, 0x4a, 0xe9, 0x3b, 0xa7, 0xfd, 0x1e, 0x7d, 0x01, 0xf0, 0xda, 0xd8,
	0x51, 0xc3, 0x75, 0xb3, 0x71, 0x13, 0xb6, 0x48, 0x36, 0x6e, 0xd2, 0x56, 0xc0, 0xdb, 0x12, 0xb7,
	0x8c, 0x36, 0xf2, 0xe0, 0xa2, 0x1f, 0x20, 0x36, 0x8e, 0x68, 0x2f, 0x47, 0x89, 0x66, 0x1f, 0x8f,
	0xf1, 0xe0, 0xbc, 0x66, 0x1a, 0xb6, 0x2e, 0x61, 0x77, 0x50, 0x95, 0xe6, 0xfa, 0xf6, 0xa8, 0xea,
	0x7e, 0x07, 0x70, 0x39, 0xe2, 0x6c, 0x58, 0xdf, 0xbd, 0x1c, 0xa5, 0xba, 0x08, 0x76, 0xf2, 0x1b,
	0xc6, 0x44, 0x62, 0x6f, 0xa2, 0x72, 0x3e, 0xec, 0xfd, 0x87, 0x27, 0x7d, 0x13, 0x9c, 0xf6, 0x4d,
	0xf0, 0xa7, 0x6f, 0x82, 0x8f, 0x03, 0xb3, 0x70, 0x3a, 0x30, 0x0b, 0x67, 0x03, 0xb3, 0xf0, 0x72,
	0x3d, 0x66, 0xf3, 0x76, 0xca, 0x5f, 0xcf, 0xe7, 0x81, 0x55, 0x92, 0x1f, 0xdc, 0xfa, 0xbf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x19, 0x0b, 0xc6, 0xb2, 0x94, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a Traceinfo by id.
	Traceinfo(ctx context.Context, in *QueryGetTraceinfoRequest, opts ...grpc.CallOption) (*QueryGetTraceinfoResponse, error)
	// Queries a list of Traceinfo items.
	TraceinfoAll(ctx context.Context, in *QueryAllTraceinfoRequest, opts ...grpc.CallOption) (*QueryAllTraceinfoResponse, error)
	// Queries a Phtraceinfo by id.
	Phtraceinfo(ctx context.Context, in *QueryGetPhtraceinfoRequest, opts ...grpc.CallOption) (*QueryGetPhtraceinfoResponse, error)
	// Queries a list of Phtraceinfo items.
	PhtraceinfoAll(ctx context.Context, in *QueryAllPhtraceinfoRequest, opts ...grpc.CallOption) (*QueryAllPhtraceinfoResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/traceability.traceability.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Traceinfo(ctx context.Context, in *QueryGetTraceinfoRequest, opts ...grpc.CallOption) (*QueryGetTraceinfoResponse, error) {
	out := new(QueryGetTraceinfoResponse)
	err := c.cc.Invoke(ctx, "/traceability.traceability.Query/Traceinfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TraceinfoAll(ctx context.Context, in *QueryAllTraceinfoRequest, opts ...grpc.CallOption) (*QueryAllTraceinfoResponse, error) {
	out := new(QueryAllTraceinfoResponse)
	err := c.cc.Invoke(ctx, "/traceability.traceability.Query/TraceinfoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Phtraceinfo(ctx context.Context, in *QueryGetPhtraceinfoRequest, opts ...grpc.CallOption) (*QueryGetPhtraceinfoResponse, error) {
	out := new(QueryGetPhtraceinfoResponse)
	err := c.cc.Invoke(ctx, "/traceability.traceability.Query/Phtraceinfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) PhtraceinfoAll(ctx context.Context, in *QueryAllPhtraceinfoRequest, opts ...grpc.CallOption) (*QueryAllPhtraceinfoResponse, error) {
	out := new(QueryAllPhtraceinfoResponse)
	err := c.cc.Invoke(ctx, "/traceability.traceability.Query/PhtraceinfoAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a Traceinfo by id.
	Traceinfo(context.Context, *QueryGetTraceinfoRequest) (*QueryGetTraceinfoResponse, error)
	// Queries a list of Traceinfo items.
	TraceinfoAll(context.Context, *QueryAllTraceinfoRequest) (*QueryAllTraceinfoResponse, error)
	// Queries a Phtraceinfo by id.
	Phtraceinfo(context.Context, *QueryGetPhtraceinfoRequest) (*QueryGetPhtraceinfoResponse, error)
	// Queries a list of Phtraceinfo items.
	PhtraceinfoAll(context.Context, *QueryAllPhtraceinfoRequest) (*QueryAllPhtraceinfoResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Traceinfo(ctx context.Context, req *QueryGetTraceinfoRequest) (*QueryGetTraceinfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Traceinfo not implemented")
}
func (*UnimplementedQueryServer) TraceinfoAll(ctx context.Context, req *QueryAllTraceinfoRequest) (*QueryAllTraceinfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TraceinfoAll not implemented")
}
func (*UnimplementedQueryServer) Phtraceinfo(ctx context.Context, req *QueryGetPhtraceinfoRequest) (*QueryGetPhtraceinfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Phtraceinfo not implemented")
}
func (*UnimplementedQueryServer) PhtraceinfoAll(ctx context.Context, req *QueryAllPhtraceinfoRequest) (*QueryAllPhtraceinfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PhtraceinfoAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traceability.traceability.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Traceinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetTraceinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Traceinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traceability.traceability.Query/Traceinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Traceinfo(ctx, req.(*QueryGetTraceinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TraceinfoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllTraceinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TraceinfoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traceability.traceability.Query/TraceinfoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TraceinfoAll(ctx, req.(*QueryAllTraceinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Phtraceinfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetPhtraceinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Phtraceinfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traceability.traceability.Query/Phtraceinfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Phtraceinfo(ctx, req.(*QueryGetPhtraceinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_PhtraceinfoAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllPhtraceinfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).PhtraceinfoAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/traceability.traceability.Query/PhtraceinfoAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).PhtraceinfoAll(ctx, req.(*QueryAllPhtraceinfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "traceability.traceability.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Traceinfo",
			Handler:    _Query_Traceinfo_Handler,
		},
		{
			MethodName: "TraceinfoAll",
			Handler:    _Query_TraceinfoAll_Handler,
		},
		{
			MethodName: "Phtraceinfo",
			Handler:    _Query_Phtraceinfo_Handler,
		},
		{
			MethodName: "PhtraceinfoAll",
			Handler:    _Query_PhtraceinfoAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "traceability/traceability/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetTraceinfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTraceinfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTraceinfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetTraceinfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetTraceinfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetTraceinfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Traceinfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllTraceinfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTraceinfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTraceinfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllTraceinfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllTraceinfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllTraceinfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Traceinfo) > 0 {
		for iNdEx := len(m.Traceinfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Traceinfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPhtraceinfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPhtraceinfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPhtraceinfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetPhtraceinfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetPhtraceinfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetPhtraceinfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Phtraceinfo.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllPhtraceinfoRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPhtraceinfoRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPhtraceinfoRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllPhtraceinfoResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllPhtraceinfoResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllPhtraceinfoResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Phtraceinfo) > 0 {
		for iNdEx := len(m.Phtraceinfo) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Phtraceinfo[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetTraceinfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetTraceinfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Traceinfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllTraceinfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllTraceinfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Traceinfo) > 0 {
		for _, e := range m.Traceinfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetPhtraceinfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetPhtraceinfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Phtraceinfo.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllPhtraceinfoRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllPhtraceinfoResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Phtraceinfo) > 0 {
		for _, e := range m.Phtraceinfo {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTraceinfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTraceinfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTraceinfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetTraceinfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetTraceinfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetTraceinfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Traceinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Traceinfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTraceinfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTraceinfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTraceinfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllTraceinfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllTraceinfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllTraceinfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Traceinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Traceinfo = append(m.Traceinfo, Traceinfo{})
			if err := m.Traceinfo[len(m.Traceinfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPhtraceinfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPhtraceinfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPhtraceinfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetPhtraceinfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetPhtraceinfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetPhtraceinfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phtraceinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Phtraceinfo.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPhtraceinfoRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPhtraceinfoRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPhtraceinfoRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllPhtraceinfoResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllPhtraceinfoResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllPhtraceinfoResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Phtraceinfo", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Phtraceinfo = append(m.Phtraceinfo, Phtraceinfo{})
			if err := m.Phtraceinfo[len(m.Phtraceinfo)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
